package:
  name: r-scplotter
  version: 0.0.1

source:
  git_url: https://github.com/pwwang/scplotter
  git_rev: 675668eec7ee3cd2f0b10bb8546425954c227387 # on 10/01/2024

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-seurat
    - pwwang::r-plotthis

  run:
    - r-base
    - r-seurat
    - pwwang::r-plotthis

test:
  commands:
    - $R -e "library('scplotter')"

about:
  home: https://github.com/pwwang/scplotter
  license: GPL-3
  summary: provides a set of functions to visualize single-cell sequencing data in an easy and efficient way.
  license_family: GPL
  license_file: LICENSE.md
