package:
  name: r-scplotter
  version: 0.2.0

source:
  git_url: https://github.com/pwwang/scplotter
  git_rev: 0.2.0

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-seurat
    - pwwang::r-plotthis
    - bioconda::bioconductor-complexheatmap
    - pwwang::bioconductor-screpertoire
    - r-clustree
    - r-ggwordcloud
    - r-ggalluvial
    - r-ggvenndiagram
    - r-ggupset
    - r-ggpubr
    - r-ggforce
    - r-ggraph
    - r-ggridges
    - r-hexbin
    - r-igraph
    - r-scattermore
    - r-concaveman
    - r-gridgraphics
    - r-inext
    - r-metap

  run:
    - r-base
    - r-seurat
    - pwwang::r-plotthis
    - bioconda::bioconductor-complexheatmap
    - pwwang::bioconductor-screpertoire
    - r-clustree
    - r-ggwordcloud
    - r-ggalluvial
    - r-ggvenndiagram
    - r-ggupset
    - r-ggpubr
    - r-ggforce
    - r-ggraph
    - r-ggridges
    - r-hexbin
    - r-igraph
    - r-scattermore
    - r-concaveman
    - r-gridgraphics
    - r-inext
    - r-metap

test:
  commands:
    - $R -e "library('scplotter')"

about:
  home: https://github.com/pwwang/scplotter
  license: GPL-3
  summary: provides a set of functions to visualize single-cell sequencing data in an easy and efficient way.
  license_family: GPL
  license_file: LICENSE.md
